package ventanas;

import aplicacion.Aplicacion;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SwingWorker;
import javax.swing.border.Border;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author mivap
 */
public class VentanaIncidenciaValidada extends javax.swing.JDialog {

    protected Aplicacion app;
    protected int idIncidencia;
    
    protected String respuestaServidor;
    protected String[] resServidor; 
    
    String[] correos, nombres;
    
public VentanaIncidenciaValidada(java.awt.Frame parent, boolean modal, Aplicacion app, int idIncidencia) {
        super(parent, modal);
        initComponents();
        
        this.app=app;
        this.idIncidencia=idIncidencia;
        
        setSize(600, 300);               
        setLocationRelativeTo(null);
                
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_ventana = new javax.swing.JPanel();
        panelUp_ventana = new javax.swing.JPanel();
        boton_salir = new javax.swing.JButton();
        imagen_logo = new javax.swing.JLabel();
        nombre_app = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxEmpleados = new javax.swing.JComboBox<>();
        progressBar = new javax.swing.JProgressBar();
        boton_aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        panel_ventana.setBackground(new java.awt.Color(240, 239, 240));
        panel_ventana.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 64, 95)));
        panel_ventana.setMinimumSize(new java.awt.Dimension(600, 300));
        panel_ventana.setPreferredSize(new java.awt.Dimension(600, 300));
        panel_ventana.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelUp_ventana.setBackground(new java.awt.Color(26, 64, 95));
        panelUp_ventana.setForeground(new java.awt.Color(255, 255, 255));
        panelUp_ventana.setPreferredSize(new java.awt.Dimension(960, 70));
        panelUp_ventana.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelUp_ventanaMouseDragged(evt);
            }
        });
        panelUp_ventana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelUp_ventanaMousePressed(evt);
            }
        });

        boton_salir.setBackground(new java.awt.Color(0, 0, 51));
        boton_salir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        boton_salir.setForeground(new java.awt.Color(255, 255, 255));
        boton_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono_cerrar_ventana.png"))); // NOI18N
        boton_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_salirMouseExited(evt);
            }
        });
        boton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salirActionPerformed(evt);
            }
        });

        imagen_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_inciapp_icono.jpg"))); // NOI18N

        nombre_app.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        nombre_app.setForeground(new java.awt.Color(255, 255, 255));
        nombre_app.setText("InciApp  -  Incidencia Validada");

        javax.swing.GroupLayout panelUp_ventanaLayout = new javax.swing.GroupLayout(panelUp_ventana);
        panelUp_ventana.setLayout(panelUp_ventanaLayout);
        panelUp_ventanaLayout.setHorizontalGroup(
            panelUp_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUp_ventanaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(imagen_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombre_app)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(boton_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        panelUp_ventanaLayout.setVerticalGroup(
            panelUp_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUp_ventanaLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelUp_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imagen_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre_app)
                    .addComponent(boton_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panel_ventana.add(panelUp_ventana, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 70));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(47, 47, 40));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccion un empleado");
        panel_ventana.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 200, 25));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(47, 47, 40));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("para arreglar la incidencia");
        panel_ventana.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 200, 25));

        jComboBoxEmpleados.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        panel_ventana.add(jComboBoxEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 310, 30));

        progressBar.setForeground(new java.awt.Color(26, 64, 95));
        panel_ventana.add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 280, 290, 10));

        boton_aceptar.setBackground(new java.awt.Color(26, 188, 156));
        boton_aceptar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        boton_aceptar.setForeground(new java.awt.Color(240, 239, 240));
        boton_aceptar.setText("Aceptar");
        boton_aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_aceptarMouseClicked(evt);
            }
        });
        panel_ventana.add(boton_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_ventana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_ventana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //      BOTON SALIR
    private void boton_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_salirMouseEntered
        Border border_boton = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.white);
        boton_salir.setBorder(border_boton);
    }//GEN-LAST:event_boton_salirMouseEntered

    private void boton_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_salirMouseExited
        Border border_boton = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        boton_salir.setBorder(border_boton);
    }//GEN-LAST:event_boton_salirMouseExited

    private void boton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salirActionPerformed
        dispose();
    }//GEN-LAST:event_boton_salirActionPerformed
    
    //      MOVER VENTANA
    int xx, xy;
    private void panelUp_ventanaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUp_ventanaMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_panelUp_ventanaMouseDragged

    private void panelUp_ventanaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUp_ventanaMousePressed
        xx=evt.getX();
        xy=evt.getY();
    }//GEN-LAST:event_panelUp_ventanaMousePressed

    //      BOTON ACEPTAR
    private void boton_aceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_aceptarMouseClicked
        //nos seguramos que tenemos seleccionado un empleado de nuestro combobox
        if(jComboBoxEmpleados.getSelectedIndex() != -1){
        
            SwingWorker workerValidarIncidencia = new SwingWorker<Void, Void>(){
                @Override
                protected Void doInBackground() throws Exception {
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);

                    respuestaServidor = app.protocoloMensajes("8||"+idIncidencia+"||"+correos[jComboBoxEmpleados.getSelectedIndex()]+"||");
                    resServidor = respuestaServidor.split("\\|\\|");

                    if(resServidor[0].equals("11") && resServidor[1].equals("empleadoAsignadoOk")){
                        dispose();
                    }

                    progressBar.setIndeterminate(false);
                    progressBar.setVisible(false);

                    return null;
                }

            };

            workerValidarIncidencia.execute();
        }
    }//GEN-LAST:event_boton_aceptarMouseClicked

    
        //  METODOS 
    public void cargarDatos(){
        
        SwingWorker workerDatos = new SwingWorker<Void, Void>(){
            @Override
            protected Void doInBackground() throws Exception {    
                ocultarComponentes();
                progressBar.setVisible(true);
                progressBar.setIndeterminate(true);                

                respuestaServidor = app.protocoloMensajes("7||"+idIncidencia+"||");                
                System.out.println(respuestaServidor);
                if(!respuestaServidor.equals("null")){
                    JSONParser parser = new JSONParser();
                    JSONObject object = (JSONObject) parser.parse(respuestaServidor);
                    
                    String listaEmpleados = object.get("empleados").toString();
                    System.out.println(listaEmpleados);
                    String[] aux;                            
                    aux = listaEmpleados.split(";");
                    nombres = new String[aux.length];
                    correos = new String[aux.length];
                    String[] nombre_correo;

                    for(int i=0; i<aux.length; i++){
                        nombre_correo = aux[i].split(":");
                        nombres[i] = nombre_correo[0];
                        correos[i] = nombre_correo[1];
                    }

                    cargarComboBoxEmpleados();
                }

                progressBar.setIndeterminate(false);
                progressBar.setVisible(false);    
                mostrarComponentes();
                return null;
            }            
        };   
        
        workerDatos.execute();
    }
    
    public void cargarComboBoxEmpleados(){
        DefaultComboBoxModel model = new DefaultComboBoxModel(nombres);
        jComboBoxEmpleados.setModel(model);
        jComboBoxEmpleados.setMaximumRowCount(nombres.length);
        jComboBoxEmpleados.setEditable(true);   
    }
    
    public void ocultarComponentes(){
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jComboBoxEmpleados.setVisible(false);
        boton_aceptar.setVisible(false);        
    }
    
    public void mostrarComponentes(){
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jComboBoxEmpleados.setVisible(true);
        boton_aceptar.setVisible(true);       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_aceptar;
    private javax.swing.JButton boton_salir;
    private javax.swing.JLabel imagen_logo;
    private javax.swing.JComboBox<String> jComboBoxEmpleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nombre_app;
    private javax.swing.JPanel panelUp_ventana;
    private javax.swing.JPanel panel_ventana;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
